"""SQLAlchemy models for the Plant Monitoring & Alert System."""

from datetime import datetime

from sqlalchemy import Boolean, Column, Date, DateTime, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from backend.app.core.database import Base


class User(Base):
    """A judge / gardener profile that can own multiple plants and locations."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    telegram_chat_id = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Authentication (nullable to preserve legacy rows created before login existed)
    hashed_password = Column(String, nullable=True)
    is_admin = Column(Boolean, nullable=False, default=False)

    # Relationships (kept lazy to avoid unexpected joins)
    plants = relationship("TrackedPlant", back_populates="user")
    locations = relationship("Location", back_populates="user")


class Location(Base):
    """A named garden plot / balcony / rooftop location owned by a user."""

    __tablename__ = "locations"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    name = Column(String, nullable=False, default="Home Garden")
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="locations")


class TrackedPlant(Base):
    """A user-registered plant being monitored for growth milestones and weather risks."""

    __tablename__ = "tracked_plants"

    id = Column(Integer, primary_key=True, index=True)
    crop_name = Column(String, nullable=False)
    planted_date = Column(Date, nullable=False)
    pot_size_liters = Column(Float, nullable=False, default=5.0)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    location_name = Column(String, nullable=True, default="Home Garden")
    telegram_chat_id = Column(String, nullable=True)
    active = Column(Boolean, nullable=False, default=True)

    # Profile ownership (nullable for backward compatibility with pre-existing rows)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)

    # Relationships
    alerts = relationship("PlantAlert", back_populates="plant", cascade="all, delete-orphan")
    user = relationship("User", back_populates="plants")


class PlantAlert(Base):
    """An alert generated by the background monitor for a tracked plant."""

    __tablename__ = "plant_alerts"

    id = Column(Integer, primary_key=True, index=True)
    plant_id = Column(Integer, ForeignKey("tracked_plants.id"), nullable=False, index=True)
    alert_type = Column(String, nullable=False)  # "milestone" or "weather"
    severity = Column(String, nullable=False, default="info")  # "info", "warning", "critical"
    message = Column(Text, nullable=False)
    action_required = Column(Text, nullable=True)
    resolved = Column(Boolean, nullable=False, default=False)
    triggered_on = Column(Date, nullable=False)

    # Relationship back to plant
    plant = relationship("TrackedPlant", back_populates="alerts")


class SystemAuditLog(Base):
    """Audit trail for autonomous background monitor executions."""

    __tablename__ = "system_audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    trigger_type = Column(String(50), default="CRON_SCHEDULED")
    action = Column(String(100))
    details = Column(Text)
    status = Column(String(20), default="SUCCESS")
