"""SQLAlchemy models for the Plant Monitoring & Alert System."""

from sqlalchemy import Boolean, Column, Date, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import relationship

from backend.app.core.database import Base


class TrackedPlant(Base):
    """A user-registered plant being monitored for growth milestones and weather risks."""

    __tablename__ = "tracked_plants"

    id = Column(Integer, primary_key=True, index=True)
    crop_name = Column(String, nullable=False)
    planted_date = Column(Date, nullable=False)
    pot_size_liters = Column(Float, nullable=False, default=5.0)
    latitude = Column(Float, nullable=False)
    longitude = Column(Float, nullable=False)
    location_name = Column(String, nullable=True, default="Home Garden")
    telegram_chat_id = Column(String, nullable=True)
    active = Column(Boolean, nullable=False, default=True)

    # Relationship to alerts
    alerts = relationship("PlantAlert", back_populates="plant", cascade="all, delete-orphan")


class PlantAlert(Base):
    """An alert generated by the background monitor for a tracked plant."""

    __tablename__ = "plant_alerts"

    id = Column(Integer, primary_key=True, index=True)
    plant_id = Column(Integer, ForeignKey("tracked_plants.id"), nullable=False, index=True)
    alert_type = Column(String, nullable=False)  # "milestone" or "weather"
    severity = Column(String, nullable=False, default="info")  # "info", "warning", "critical"
    message = Column(Text, nullable=False)
    action_required = Column(Text, nullable=True)
    resolved = Column(Boolean, nullable=False, default=False)
    triggered_on = Column(Date, nullable=False)

    # Relationship back to plant
    plant = relationship("TrackedPlant", back_populates="alerts")
